name: Gradle Assemble

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  assemble:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up JDK
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # Step 3: Set up Gradle cache
      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}

      # Step 4: Ensure gradlew is executable
      - name: Grant execute permission for Gradle wrapper
        run: chmod +x gradlew

      # Step 5: Run the Gradle assemble task
      - name: Assemble the project
        run: ./gradlew assemble
