name: Distribute Compose App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-distribute:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [android, desktop]
        include:
          - target: android
            gradle_task: assembleRelease
            artifact_name: app-release.apk
            artifact_path: app/build/outputs/apk/release/app-release.apk
          - target: desktop
            gradle_task: packageRelease
            artifact_name: app-desktop.zip
            artifact_path: app/build/distributions/app-desktop.zip

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up JDK
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # Set up caching for Gradle
      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}

      # Ensure gradlew has executable permissions
      - name: Grant execute permission for Gradle wrapper
        run: chmod +x gradlew

      # Build the application
      - name: Build for ${{ matrix.target }}
        run: ./gradlew ${{ matrix.gradle_task }}

      # Upload artifacts
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.artifact_name }}
          path: ${{ matrix.artifact_path }}
